repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.5
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_tfsec
        args:
          - --args=--format=json
      - id: checkov
        args: [--framework=terraform]

  - repo: https://github.com/semgrep/semgrep
    rev: v1.134.0
    hooks:
      - id: semgrep
        args: [--config=p/terraform, --config=p/secrets, --error]